# Generated by Django 3.1 on 2020-09-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='pubdate',
            new_name='pub_date',
        ),
    ]
